config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index , :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get '/search' => 'pages#search', :as => 'search_page'
  resources :articles do
    resources :comments, only: [:show, :index , :new, :create, :edit, :update]
  end
  resources :comments, only: [:destroy]
  
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :articles_categories
    has_many :categories, through: :articles_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 10000 }
    has_attached_file :image
    has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def show
    @article = Article.find(params[:id])
    @articlenew = Article.order("created_at DESC")
    @comments = @article.comments
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  
  def index
    @articles = Article.order("created_at DESC").paginate(page: params[:page], per_page: 5)
    
  end
  
  def new
      @article = Article.new
  end
  
  
  def edit
      @article = Article.find(params[:id])
  end
  
  def create
        @article = Article.new(params.require(:article).permit(:title, :description, :image, category_ids: []))
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article is successfully created"
            redirect_to @article
        else
            render 'new' 
        end
        
  end
  
  def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description, :image, category_ids: []))
            flash[:notice] = "Article is updated successfully."
            redirect_to @article
        else
            render 'edit'
        end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  
  
  private
  
  def require_same_user
    if current_user != Article.find(params[:id]).user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to Article.find(params[:id])
    end
  end
  
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %></div> 
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/articles/_forms.html.erb
      <div class="row justify-content-center">
          <%= render 'shared/errors', obj: @article %>
         <div class="col-10">
             
          <%= form_with(model: @article, local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :title, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= f.text_field :title, class:"form-control",  placeholder: "Title of article" %>
            </div>
          </div>
          <div class="form-group row">
              <%= f.label :description, class:"col-sm-2 col-form-label"%> 
              <div class="col-sm-10">
              <%= f.text_area :description, rows:10, class:"form-control" ,  placeholder: "Description of article"%> 
              </div>
          </div>
          
          <div class="form-group row">
              <%= f.label :category, class:"col-sm-2 col-form-label"%> 
              <div class="col-sm-10">
                <%= f.collection_select(:category_ids, Category.all, :id, :name,
              { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
              </div>
          </div>
          
          <div class="form-group row">
              <%= f.label :image, class:"col-sm-2 col-form-label"%> 
              <div class="col-sm-10">
              <%= f.file_field :image, class:"form-control" ,  placeholder: "File Image"%> 
              </div>
          </div>
          <div class="form-group row justify-content-center">
              <%= f.submit class: "btn btn btn-success"%> 
            </div>
          <% end %>
          <div class = "mb-3">
            <%= link_to 'Return to articles listing', articles_path,  class:"text-info col-2"  %> 
        </div>
    </div>

app/views/articles/edit.html.erb
<div id="page-content">
  <div class = "container">
  <h1 class="text-center mt-4">Edit the article</h1>
    <%= render 'forms' %>
  </div>
</div>

app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Listing all articles</h1>
  <div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'article' %>
  <div class="apple_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <div class = "container">
  <h1 class="text-center mt-4">Create a new article</h1>
    <%= render 'forms' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4"><%= @article.title %></h1>
        <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div> 
          <% end %>

        <!-- Author -->
        <p class="lead">
          by
          <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Created <%= time_ago_in_words(@article.created_at) %> ago | Edited <%= time_ago_in_words(@article.updated_at) %> ago</p>

        <hr>

        <!-- Preview Image -->
        <%= image_tag(@article.image.url, class:"img-responsive")%>

        <hr>

        <!-- Post Content -->
        

        <%= simple_format(@article.description) %>
        <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>
        
        <hr>

        <!-- Comments Form -->
        <%= render partial: 'comments/form' %>

        <!-- Single Comment -->
        <% if @article.comments.any? %>
          <% @comments.each do |comment| %>
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0"><%= comment.author_name %></h5>
              <%= comment.body %>
              <br>
              <% if current_user.username == comment.author_name || current_user.admin? %>
                <br>
                <%= link_to "Delete", comment_path(comment), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
              <% end %>
              </div>
              <small>Commented <%= time_ago_in_words(comment.created_at) %> ago</small>
              
              <br>
          </div>
          <hr>
          <% end %>
        <% end %>

        <!-- Comment with nested comments -->
        

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        
        

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">New Articles</h5>
          <div class="card-body">
            <% count = 0 %>
            <% @articlenew.each do |article| %>
              <% count = count+1 %>
              <% break if count>3 %>
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                <h5 class="card-title"><%= article.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><small>Created <%= time_ago_in_words(article.created_at) %> ago</small></h6>
                <p class="card-text"><%= truncate(article.description, length: 150) %></p>
                <a href="#" class="card-link"><%= link_to "Read More", article_path(article) %></a>
                </div>
              </div>
              <br>
            <% end %>
            <%= link_to 'View all Articles', articles_path,  class:"btn btn-primary"  %> 
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>