config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index , :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get '/search' => 'pages#search', :as => 'search_page'
  resources :articles do
    resources :comments, only: [:show, :index , :new, :create, :edit, :update]
  end
  resources :comments, only: [:destroy]
  
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true , length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :articles_categories
    has_many :articles, through: :articles_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    
    end
    
    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.order("created_at DESC").paginate(page: params[:page], per_page: 5)
    end
    
    def edit
        @category = Category.find(params[:id])
    end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end
    
    private

    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
        if !(logged_in? && current_user.admin?)
          flash[:alert] = "Only admins can perform that action"
          redirect_to categories_path
        end
    end
  
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %> 

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
         <div class="col-10">
             
          <%= form_with(model: @category, local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :name, "Category Name", class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= f.text_field :name, class:"form-control",  placeholder: "Enter a category name" %>
            </div>
          </div>
          <div class="form-group row justify-content-center">
              <%= f.submit class: "btn btn btn-success" %> 
            </div>
          <% end %>
          
    </div>

app/views/categories/edit.html.erb
<div id="page-content">
  <div class = "container">
  <h1 class="text-center mt-4">Edit Category Name</h1>
  <br>
  <br>
      <div class="row justify-content-center">
          <%= render 'form' %>
  </div>
  <div class = "mb-3">
            <%= link_to 'Return to category listing', category_path(@category),  class:"text-info col-2"  %> 
        </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/categories/new.html.erb
<div id="page-content">
  <div class = "container">
  <h1 class="text-center mt-4">Create a new Category</h1>
  <br>
  <br>
      <div class="row justify-content-center">
          <%= render 'form' %>
  </div>
  <div class = "mb-3">
            <%= link_to 'Return to category listing', categories_path,  class:"text-info col-2"  %> 
        </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1> 
<div class="text-center mt-4">
      <% if logged_in? && current_user.admin? %>
      <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-outline-info" %>
      <% end %>
    </div>
    <h3 class="text-center mt-4">Articles</h3>
    <div class="apple_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'articles/article' %>
    <div class="apple_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>